// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsvW-S20Xj6JPGrT7DraL1iPIxR6m-sNQ',
    appId: '1:364034107308:web:4e099e6a8495b9112b3c09',
    messagingSenderId: '364034107308',
    projectId: 'clan-be918',
    authDomain: 'clan-be918.firebaseapp.com',
    storageBucket: 'clan-be918.firebasestorage.app',
    measurementId: 'G-WM1FD10R76',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmmBWNlohG0Lr610FXjdXQ2cRWzRXwHJ8',
    appId: '1:364034107308:android:82210434865a61402b3c09',
    messagingSenderId: '364034107308',
    projectId: 'clan-be918',
    storageBucket: 'clan-be918.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQnx0hmijGsDktrayV88-mc6V-DW3oVXA',
    appId: '1:364034107308:ios:a20017bcd487538b2b3c09',
    messagingSenderId: '364034107308',
    projectId: 'clan-be918',
    storageBucket: 'clan-be918.firebasestorage.app',
    iosBundleId: 'com.clanship.clanshipMobileTradesman',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQnx0hmijGsDktrayV88-mc6V-DW3oVXA',
    appId: '1:364034107308:ios:a20017bcd487538b2b3c09',
    messagingSenderId: '364034107308',
    projectId: 'clan-be918',
    storageBucket: 'clan-be918.firebasestorage.app',
    iosBundleId: 'com.clanship.clanshipMobileTradesman',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsvW-S20Xj6JPGrT7DraL1iPIxR6m-sNQ',
    appId: '1:364034107308:web:2c6a8af3b3aafe102b3c09',
    messagingSenderId: '364034107308',
    projectId: 'clan-be918',
    authDomain: 'clan-be918.firebaseapp.com',
    storageBucket: 'clan-be918.firebasestorage.app',
    measurementId: 'G-RBQQV47QSE',
  );
}
